// Import React dependencies
//--------------------------------------------------------
import React, {Component} from 'react';
import './Container.css';
import { Row } from '../Row';
import { Title } from '../Title';
import { Col } from '../Col';
import { Paragraph } from '../Paragraph';


// Create new stateful component
//--------------------------------------------------------
class Container extends Component{
    
	state = {

	}

	render(){
		return(

			<div className='container'>
				
				<Row>
 					<Title>
						Welcome to the Fision Application
  					</Title>
 				</Row>
 				<Row>
 					<Col>
 						<Paragraph>
							This is a sample view generated by the application
  						</Paragraph>
						<Paragraph>
							This is a sample view generated by the application
  						</Paragraph>
 					</Col>
					<Col>
 						<Paragraph>
							This is a sample view generated by the application
  						</Paragraph>
						<Paragraph>
							This is a sample view generated by the application
  						</Paragraph>
 					</Col>
 				</Row>

			</div>
		)
	}
};


// Export component to application
//--------------------------------------------------------
export {Container};

