// Import React dependencies
//--------------------------------------------------------
import React, { Component } from 'react';
import './Container.css';
import { Row } from '../Row';
import { Title } from '../../Text';
import { Col } from '../Col';
import { Paragraph } from '../../Text';


// Create new stateful component
//--------------------------------------------------------
class Container extends Component{
    
	state = {

	}

	render(){
		return(

			<div className={`container ${this.props.fluid}`}>
				
				<Row >
 					<Title >
						Welcome to Fission
  					</Title>
 				</Row>
 				<Row >
 					<Col size={ "s6" }>
 						<Paragraph >
							This was generated by the application
  						</Paragraph>
						<Paragraph >
							Learn more about the Chain-React.ion Team!
  						</Paragraph>
 					</Col>
					<Col size={ "s6" }>
 						<Paragraph >
							Framework is from MaterializeCSS
  						</Paragraph>
						<Paragraph >
							Generate React components with ease!
  						</Paragraph>
 					</Col>
 				</Row>

			</div>
		)
	}
};


// Export component to application
//--------------------------------------------------------
export {Container};

