// Import React dependencies
//--------------------------------------------------------
import React from 'react';
import './Paragraph.css';


// Create stateless component
//--------------------------------------------------------
const Paragraph = (props) =>

	<p className='paragraph'>

		This is a sample view generated by the application

	</p>

// Export component to application
//--------------------------------------------------------
export { Paragraph };
