// Import React dependencies
//--------------------------------------------------------
import React, { Component } from 'react';
import './App.css';
import { Container } from '../components/Container'
import { Row } from '../components/Row'
import { Title } from '../components/Title'
import { Col } from '../components/Col'
import { Paragraph } from '../components/Paragraph'


// Create App component
//--------------------------------------------------------

class App extends Component {
	render() {

		return (

			<Container>

				<Row>

					<Title>

						Welcome to the PRC Application

					</Title>

				</Row>

				<Row>

					<Col>

						<Paragraph>

							This is a sample view generated by the application

						</Paragraph>

					</Col>

				</Row>

			</Container>

		);
	}
}

export {App};
